from pathlib import Path
import sys
sys.path.insert(0, str(Path.cwd() / "scripts"))
from native_probe_storage import probe_source, identity_json
import hashlib,json
out=Path('.agentplane/tasks/202610011419-EHEH05');root=Path('vendor/libreoffice-reference');ids=[]
def body(path,sig):
 source=(root/path).read_text();a=source.index(sig);i=source.index('{',a)+1;depth=1
 while depth:
  depth+=(source[i]=='{')-(source[i]=='}');i+=1
 value=source[a:i];ids.append({'path':path,'signature':sig,'sha256':hashlib.sha256(value.encode()).hexdigest()});return value
profile=probe_source(Path('.agentplane/tasks/202610011338-WSMJ80/native-pointer.cxx')).read_text().split('void boolout(')[0]
profile=profile.replace('using sal_Int32=int32_t;','using sal_uInt32=uint32_t;using sal_Int32=int32_t;')
profile=profile.replace('namespace SwPoolFormatId {constexpr int UNKNOWN=0;}','enum class SwPoolFormatId:sal_uInt16 {UNKNOWN=USHRT_MAX};')
source=(root/'sw/inc/poolfmt.hxx').read_text();assert 'UNKNOWN = USHRT_MAX' in source
ids.append({'path':'sw/inc/poolfmt.hxx','signature':'enum class SwPoolFormatId : sal_uInt16; UNKNOWN = USHRT_MAX','sha256':hashlib.sha256(source.encode()).hexdigest()})
profile=profile.replace('int mnPoolFormatId,mnPoolHelpId,mnPoolHlpFileId;','SwPoolFormatId mnPoolFormatId;sal_uInt16 mnPoolHelpId;sal_uInt8 mnPoolHlpFileId;')
start=profile.index('int GetPoolFormatId()const');end=profile.index('\n};',start)
profile=profile[:start]+''.join(body('sw/inc/numrule.hxx',sig)+'\n' for sig in ['bool IsHidden(', 'void SetHidden(', 'bool IsAutoRule()', 'void SetAutoRule(', 'bool IsInvalidRule()', 'void Invalidate()', 'bool IsContinusNum()', 'void SetContinusNum(', 'bool IsAbsSpaces()', 'void SetAbsSpaces(', 'bool IsCountPhantoms()', 'bool IsUsedByRedline()', 'void SetUsedByRedline(', 'SwPoolFormatId GetPoolFormatId()', 'void SetPoolFormatId(', 'sal_uInt16 GetPoolHelpId()', 'void SetPoolHelpId(', 'sal_uInt8 GetPoolHlpFileId()', 'void SetPoolHlpFileId('])+ 'SwNumRule&operator=(const SwNumRule&);void Reset(const UIName&);bool operator==(const SwNumRule&)const;void SetCountPhantoms(bool);std::vector<int>maTextNodeList,maParagraphStyleList;'+profile[end:]
for sig in ['SwNumRule::SwNumRule( UIName','SwNumRule::SwNumRule( const SwNumRule&','const SwNumFormat& SwNumRule::Get(','const SwNumFormat* SwNumRule::GetNumFormat(','void SwNumRule::Set( sal_uInt16 i, const SwNumFormat&','void SwNumRule::Set( sal_uInt16 i, const SwNumFormat*']:
 assert body('sw/source/core/doc/number.cxx',sig) in profile
for sig in ['SwNumRule& SwNumRule::operator=(', 'void SwNumRule::Reset(', 'bool SwNumRule::operator==(', 'void SwNumRule::SetCountPhantoms(']:
 profile+=body('sw/source/core/doc/number.cxx',sig)+'\n'
prior=probe_source(Path('.agentplane/tasks/202610011338-WSMJ80/native-pointer.cxx')).read_text();profile+=prior[prior.index('void boolout('):prior.index('void change(')]
profile+=r'''
void scalar(SwNumRule&r,int n){r.SetAutoRule(n%2==0);r.SetContinusNum(n%2);r.SetAbsSpaces(n%3);r.SetHidden(n%2);r.SetCountPhantoms(n%2==0);r.SetUsedByRedline(n%2);r.SetPoolFormatId(static_cast<SwPoolFormatId>(60000+n));r.SetPoolHelpId(65530+n);r.SetPoolHlpFileId(250+n);}
void seed(SwNumRule&r,int mask,int offset){for(int n=0;n<MAXLEVEL;n++)if(mask&(1<<n)){SwNumFormat f(r.Get(n));f.SetStart(offset+n);f.SetPrefix("[");r.Set(n,f);}}
void rule(SwNumRule&r){std::cout<<"{\"meta\":[\""<<r.msName.value<<"\","<<r.meRuleType<<",";boolout(r.IsAutoRule());std::cout<<",";boolout(r.IsInvalidRule());std::cout<<",";boolout(r.IsContinusNum());std::cout<<",";boolout(r.IsAbsSpaces());std::cout<<",";boolout(r.IsHidden());std::cout<<",";boolout(r.IsCountPhantoms());std::cout<<",";boolout(r.IsUsedByRedline());std::cout<<","<<int(r.GetPoolFormatId())<<","<<r.GetPoolHelpId()<<","<<int(r.GetPoolHlpFileId())<<","<<r.meDefaultNumberFormatPositionAndSpaceMode<<",\""<<r.msDefaultListId.value<<"\","<<r.maTextNodeList.size()<<","<<r.maParagraphStyleList.size()<<"],\"owned\":[";for(int n=0;n<10;n++){if(n)std::cout<<",";boolout(r.GetNumFormat(n)!=nullptr);}std::cout<<"],\"values\":[";for(int n=0;n<10;n++){if(n)std::cout<<",";state(r.Get(n));}std::cout<<"]}";}
int main(){std::cout<<"{\"traces\":[";bool comma=false;for(int mode:{0,1})for(int type:{0,1})for(int n:{0,1,7})for(int mask:{0,341,682,1023}){
 SwNumRule target("target",static_cast<SvxNumberFormat::SvxNumPositionAndSpaceMode>(mode),type),source("source",static_cast<SvxNumberFormat::SvxNumPositionAndSpaceMode>(1-mode),1-type);target.msDefaultListId="target-list";source.msDefaultListId="source-list";target.maTextNodeList={1,2};target.maParagraphStyleList={3};source.maTextNodeList={4};source.maParagraphStyleList={5,6};seed(target,511,2);seed(source,mask,7);scalar(target,n+2);scalar(source,n);target.mbInvalidRuleFlag=false;source.mbInvalidRuleFlag=false;
 const SwNumFormat*held[10];for(int i=0;i<10;i++)held[i]=target.GetNumFormat(i);
 if(comma)std::cout<<",";comma=true;std::cout<<"{\"mode\":"<<mode<<",\"type\":"<<type<<",\"scalar\":"<<n<<",\"mask\":"<<mask<<",\"source\":";rule(source);std::cout<<",\"before\":";rule(target);SwNumRule copy(source);std::cout<<",\"copy\":";rule(copy);bool identity=&(target=source)==&target;std::cout<<",\"returnSame\":";boolout(identity);std::cout<<",\"assigned\":";rule(target);std::cout<<",\"same\":[";for(int i=0;i<10;i++){if(i)std::cout<<",";boolout(held[i]!=nullptr&&held[i]==target.GetNumFormat(i));}std::cout<<"],\"equal\":";boolout(target==source);target.mbInvalidRuleFlag=false;target=target;std::cout<<",\"self\":";rule(target);target=source;std::cout<<",\"equalAssigned\":";rule(target);target.Reset("");std::cout<<",\"reset\":";rule(target);SwNumRule emptyCopy(target);std::cout<<",\"emptyCopy\":";rule(emptyCopy);target.Reset("");std::cout<<",\"repeated\":";rule(target);std::cout<<"}";
 }
 std::cout<<"],\"equality\":[";comma=false;for(int variant=0;variant<18;variant++){SwNumRule a("equal",SvxNumberFormat::LABEL_ALIGNMENT),b(a);switch(variant){case 1:b.meRuleType=OUTLINE_RULE;break;case 2:b.msName="other";break;case 3:b.SetAutoRule(false);break;case 4:b.SetContinusNum(true);break;case 5:b.SetAbsSpaces(true);break;case 6:b.SetPoolFormatId(static_cast<SwPoolFormatId>(2));break;case 7:b.SetPoolHelpId(2);break;case 8:b.SetPoolHlpFileId(2);break;case 9:b.SetHidden(true);break;case 10:b.mbInvalidRuleFlag=false;break;case 11:b.SetCountPhantoms(false);break;case 12:b.SetUsedByRedline(true);break;case 13:b.msDefaultListId="other";break;case 14:b.Set(4,b.Get(4));break;case 15:{SwNumFormat f(b.Get(4));f.SetStart(7);b.Set(4,f);break;}case 16:b.meDefaultNumberFormatPositionAndSpaceMode=SvxNumberFormat::LABEL_WIDTH_AND_POSITION;break;case 17:a.meRuleType=OUTLINE_RULE;b.meRuleType=OUTLINE_RULE;a.meDefaultNumberFormatPositionAndSpaceMode=SvxNumberFormat::LABEL_WIDTH_AND_POSITION;for(int i=0;i<10;i++)a.Set(i,b.Get(i));break;}if(comma)std::cout<<",";comma=true;boolout(a==b);}
 std::cout<<"],\"narrowing\":[";comma=false;for(int n:{-1,0,255,256,65535,65536,70001}){SwNumRule r("narrow",SvxNumberFormat::LABEL_ALIGNMENT);r.mbInvalidRuleFlag=false;r.SetPoolFormatId(static_cast<SwPoolFormatId>(n));r.SetPoolHelpId(n);r.SetPoolHlpFileId(n);if(comma)std::cout<<",";comma=true;std::cout<<"["<<n<<","<<int(r.GetPoolFormatId())<<","<<r.GetPoolHelpId()<<","<<int(r.GetPoolHlpFileId())<<",";boolout(r.IsInvalidRule());std::cout<<"]";}std::cout<<"],\"default\":";SwNumRule d("default",SvxNumberFormat::LABEL_ALIGNMENT);rule(d);std::cout<<"}";
}
'''
(probe_source(out/'native-rule.cxx')).write_text(profile)
(out/'native-identities.json').write_text(identity_json({'pin':'9bc445578031fecf56086729d8e4940c77e14d65','definitions':ids,'priorProfiles':['.agentplane/tasks/202610011338-WSMJ80/native-identities.json','.agentplane/tasks/202610011207-TR9DSM/native-source-identities.json'],'profileSha256':hashlib.sha256(profile.encode()).hexdigest(),'scope':'Complete unchanged native rule ctor/copy/operator=/Reset/operator==/ref Set/pointer Set/Get bodies and exact scalar inline contracts; native UNKNOWN65535 and native ushort/byte field types. Named source client-container sizes (input vectors),invalid flag direct input,ASCII UIName,Font family/COW,platform/global service/graphics/null-style adapters. Complete native clients/styles/name map/grf links/GrabBag/Font/graphics/destructor/service lifetime and nondefault continuous/phantom consumers are not certified.'},indent=2)+'\n')
