from pathlib import Path
import json
summary='Iteration44 restores SvxNumberType -> SvxNumberFormat -> SwNumFormat constructor/copy/state ownership, native numeric type IDs, standalone SVX_DEF_BULLET U+F095, unsigned32 glyph, show-symbol state and optional copied const Font family values. SwClient is composed because JavaScript has one superclass; the currently exposed registration remains null. Explicit browser format assembly/projection replaces kind/string-glyph constructor overloads. Worker graph16 preserves font presence (including present-empty), raw glyph and visibility with historical omissions supported. Complete unchanged native bodies compare 21 format-value states and144 type/format traces under ASan/UBSan, using named null-client, family-only Font/COW, decimal-provider, string/property/locale/platform adapters. Full native service initialization/static destruction, registered style clients, other Font attributes/equality, graphics, legal-rule state and wider numbering families remain unverified. No whole-module/status or goal promotion; registered I/O deviations unchanged.'
new=[('apps/office/src/editeng/inc/svxenum.ts','include/editeng/svxenum.hxx',['SvxNumType'],['SvxNumType'], 'Only existing numeric family IDs (ARABIC4, NONE5, CHAR_SPECIAL6 and bitmap8 predicate) are represented; wider native enum families remain unimplemented.'),('apps/office/src/vcl/source/font/font.ts','vcl/source/font/font.cxx',['Font','ConstFont'],['Font::Font','Font::SetFamilyName','Font::GetFamilyName'],'Only the existing font-family scalar, default-empty, copy/COW and family equality adapter are represented. Native full Font attributes/equality/metrics/global lifetime remain unimplemented or unverified.')]
p=Path('docs/program/source-provenance.json');data=json.loads(p.read_text())
for path,up,local,symbols,omitted in new:
 data['entries'].append({'classification':'upstream-mechanism','evidence':{'local':[{'path':path,'marker':local[0]},{'path':'apps/office/src/sw/source/core/doc/number-format.test.ts','marker':'matches native standalone defaults and unsigned glyph copies'}],'upstream':[{'path':'vendor/libreoffice-reference/'+up,'marker':symbols[0]}]},'localPath':path,'localSymbols':local,'omittedResponsibilities':[omitted],'preservedResponsibilities':[summary],'status':'mapped','upstreamPath':up,'upstreamSymbols':symbols})
for e in data['entries']:
 if e['localPath'] in ['apps/office/src/editeng/source/items/numitem.ts','apps/office/src/sw/source/core/doc/number.ts','apps/office/src/sw/browser/filter/xml/writer-document-codec.ts']:
  e['evidence']['local'].append({'path':'apps/office/src/sw/source/core/doc/number-format.test.ts','marker':'matches native NumberType formatting visibility legal coercion and signed32 input'})
  if e['status']=='mapped': e['preservedResponsibilities'].append(summary)
  else:e['responsibilities'].append(summary)
  if e['localPath'].endswith('/numitem.ts'):e['localSymbols'].extend(['SvxNumberType','SVX_DEF_BULLET']);e['upstreamSymbols'].extend(['SvxNumberType::SvxNumberType','SvxNumberType::GetNumStr','SvxNumberFormat::SetBulletFont'])
data['entries'].sort(key=lambda e:e['localPath']);p.write_text(json.dumps(data,indent=2)+'\n')
p=Path('docs/program/parity/runtime-inventory.json');data=json.loads(p.read_text())
for path,up,local,symbols,omitted in new:
 data['modules'].append({'path':path,'classification':'upstream-mechanism','state':'active','suite':'shared','subsystem':'formatting-model','capabilityIds':['CAP-0112'],'semantic':{'behaviorStatus':'unverified','contractStatus':'unverified','defaultStatus':'unverified','divergenceClass':'none','evidence':[path+'#'+local[0],'vendor/libreoffice-reference/'+up+'#'+symbols[0],'apps/office/src/sw/source/core/doc/number-format.test.ts#matches native optional font copies and value equality'],'justification':summary+' '+omitted,'knownViolations':[],'localSymbols':local,'sourceResponsibility':'unverified','upstreamFile':up,'upstreamSymbols':symbols}})
for e in data['modules']:
 if e['path'] in ['apps/office/src/editeng/source/items/numitem.ts','apps/office/src/sw/source/core/doc/number.ts','apps/office/src/sw/browser/filter/xml/writer-document-codec.ts']:
  e['semantic']['justification']+=' '+summary;e['semantic']['evidence'].append('apps/office/src/sw/source/core/doc/number-format.test.ts#matches native standalone defaults and unsigned glyph copies')
  if e['path'].endswith('/numitem.ts'):e['semantic']['localSymbols'].append('SvxNumberType');e['semantic']['upstreamSymbols'].append('SvxNumberType')
data['modules'].sort(key=lambda e:e['path']);p.write_text(json.dumps(data,indent=2)+'\n')
p=Path('scripts/check-lo-source-tree.mjs');s=p.read_text().replace('const requiredFiles = [','const requiredFiles = [\n  "apps/office/src/editeng/inc/svxenum.ts",\n  "apps/office/src/vcl/source/font/font.ts",');p.write_text(s)
p=Path('docs/program/source-tree.md');s=p.read_text();s+='\nThe standalone numbering hierarchy now uses `editeng/inc/svxenum.ts` against\n`include/editeng/svxenum.hxx` and `vcl/source/font/font.ts` against\n`vcl/source/font/font.cxx`. The represented Font value is bounded to family\nname and copy-on-write handles; full native font attributes remain unverified.\n';p.write_text(s)
