import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import ts from 'typescript';
const file='apps/office/src/xmloff/source/style/xmltabi.ts';
const old=ts.createSourceFile(file,execFileSync('git',['show',`6663be3667ed69315bbfb2b332e4a0b3f640c6e3:${file}`],{encoding:'utf8'}),ts.ScriptTarget.Latest,true);
const current=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true);
const printer=ts.createPrinter({removeComments:true});
const render=(node,source)=>printer.printNode(ts.EmitHint.Unspecified,node,source);
const findClass=(source,name)=>source.statements.find(n=>ts.isClassDeclaration(n)&&n.name?.text===name);
const findMethod=(type,name)=>type.members.find(n=>ts.isMethodDeclaration(n)&&n.name.getText()===name);
const oldContainer=findClass(old,'SvxXMLTabStopImportContext');
const container=findClass(current,'SvxXMLTabStopImportContext');
const leaf=findClass(current,'SvxXMLTabStopContext_Impl');
assert(leaf && container);
const previous=findMethod(oldContainer,'createFastChildContext').body.statements;
const constructor=leaf.members.find(ts.isConstructorDeclaration).body.statements;
assert.deepEqual(previous.slice(1,-2).map(n=>render(n,old)),constructor.slice(1,-1).map(n=>render(n,current)));
assert.equal(render(previous.at(-2).expression.arguments[0],old),render(constructor.at(-1).expression.right,current));
const getter=findMethod(leaf,'getTabStop');
assert.equal(getter.body.statements[0].expression.getText(current),'this.tabStop');
const factory=findMethod(container,'createFastChildContext').body.statements;
const binding=factory[1].declarationList.declarations[0];
assert.equal(binding.initializer.expression.getText(current),'SvxXMLTabStopContext_Impl');
assert.equal(factory[2].expression.expression.getText(current),'this.maTabStops.push');
assert.equal(factory[2].expression.arguments[0].getText(current),binding.name.text);
assert.equal(factory[3].expression.getText(current),binding.name.text);
const oldSelection=findMethod(oldContainer,'endFastElement').body.statements.find(ts.isForOfStatement).statement.statements;
const selection=findMethod(container,'endFastElement').body.statements.find(ts.isForOfStatement).statement.statements;
assert.equal(selection[0].declarationList.declarations[0].initializer.expression.getText(current),'context.getTabStop');
assert.deepEqual(oldSelection.map(n=>render(n,old)),selection.slice(1).map(n=>render(n,current)));
console.log('AST comparison passed: attribute parsing, complete tab value initializer and Default-selection predicates unchanged.');
console.log('Parent creates, stores and returns the same leaf context; end selection reads leaf.getTabStop; leaf owns its readonly value.');
console.log('Native source owns tab values in SvxXMLTabStopContext_Impl and context references in maTabStops.');
console.log('Residual: native base null children are skipped by SAX; current dispatcher rejects known null children. Existing ignore-context base preserves leaf subtree outcomes without claiming dispatcher parity.');
