import { writeFileSync } from 'node:fs';
import { SwDoc } from '../../../apps/office/src/sw/source/core/doc/doc';
import { SwNumRuleItem } from '../../../apps/office/src/sw/source/core/para/paratr';
import { SfxItemSet } from '../../../apps/office/src/svl/source/items/itemset';
import { SfxInt16Item } from '../../../apps/office/src/svl/source/items/intitem';
import { SfxBoolItem } from '../../../apps/office/src/svl/source/items/cenumitm';
const doc=new SwDoc(),node=doc.paragraphs[0]!;doc.EnsureNumRule('Counters','numbered');
const snapshot=()=>({outline:node.GetAttrOutlineLevel(),empty:node.IsEmptyListStyleDueToSetOutlineLevelAttr(),rule:node.GetNumRule()?.GetName()??null,owned:node.GetNum()?.GetNumRule()?.GetName()??null,items:Object.fromEntries((node.GetpSwAttrSet()?.entries()??[]).map(i=>[i.Which(),i.QueryValue()]))});
node.SetAttrOutlineLevel(4);const positive=snapshot();
node.SetEmptyListStyleDueToSetOutlineLevelAttr();node.SetAttr(new SwNumRuleItem('Counters'));const explicit=snapshot();
node.SetAttrOutlineLevel(0);const zero=snapshot();node.ResetAttr(80);const reset=snapshot();node.ResetAllAttr();const all=snapshot();
const numbered=doc.GetTextFormatColl('text-body');numbered.SetFormatAttr(new SwNumRuleItem('Counters'));node.ChgFormatColl(numbered);const retained=node.GetNum();const removedAbsentId=node.ResetAttr(83),sameRecord=node.GetNum()===retained;
const set=new SfxItemSet(doc.GetAttrPool());set.Put(new SfxInt16Item(84,1));set.Put(new SfxBoolItem(85,true));set.Put(new SfxInt16Item(86,7));node.SetAttr(set);const batch={...snapshot(),vector:node.GetNumberVector(),cached:node.GetNum()?.GetNumber(false)};
const result={positive,explicit,zero,reset,all,absentId:{removedAbsentId,sameRecord},batch};writeFileSync('.agentplane/tasks/202610010735-THRTCH/baseline.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
