import { writeFileSync } from 'node:fs';
import { createWriterDocument } from '../../../apps/office/src/sw/source/core/doc/doc';
import { applyWriterParagraphList } from '../../../apps/office/src/sw/source/core/doc/list';
const document=createWriterDocument();
const first=document.paragraphs[0]!;const second=document.nodes.MakeTextNode();
for(const node of [first,second])applyWriterParagraphList(node,{kind:'numbered',level:0,styleId:'Counters',listId:'native-list'});
const list=document.GetDocumentListsManager().GetListByName('native-list')!;
const before={attached:list.GetListItem(first)!.GetParent()!==undefined,vector:list.GetListItemNumberVector(second),number:list.GetListItemNumber(second)};
first.GetListItemNumber();const item=list.GetListItem(second);const root=item!.GetRoot();
second.SetAttrListLevel(1);second.GetListItemNumber();
const after={sameItem:item===list.GetListItem(second),sameRoot:root===list.GetListItem(second)!.GetRoot(),vector:list.GetListItemNumberVector(second)};
writeFileSync('.agentplane/tasks/202610010418-7548FA/baseline.json',JSON.stringify({before,after},null,2)+'\n');
console.log({before,after});
