/** @fileoverview Defines compact namespace/local-name tokens for the browser fast SAX importer. */

/** ODF namespace URIs understood by the bounded Writer filter. */
export const ODF_NAMESPACES = {
  dc: "http://purl.org/dc/elements/1.1/",
  fo: "urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0",
  loext: "urn:org:documentfoundation:names:experimental:office:xmlns:loext:1.0",
  meta: "urn:oasis:names:tc:opendocument:xmlns:meta:1.0",
  office: "urn:oasis:names:tc:opendocument:xmlns:office:1.0",
  style: "urn:oasis:names:tc:opendocument:xmlns:style:1.0",
  svg: "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0",
  text: "urn:oasis:names:tc:opendocument:xmlns:text:1.0",
  xml: "http://www.w3.org/XML/1998/namespace",
  xlink: "http://www.w3.org/1999/xlink",
} as const;

/** Stable tokens for the supported ODF element and attribute vocabulary. */
export enum XMLToken {
  UNKNOWN = 0,
  OFFICE_DOCUMENT_STYLES,
  OFFICE_DOCUMENT_CONTENT,
  OFFICE_DOCUMENT_META,
  OFFICE_STYLES,
  OFFICE_AUTOMATIC_STYLES,
  OFFICE_BODY,
  OFFICE_TEXT,
  OFFICE_META,
  OFFICE_FONT_FACE_DECLS,
  OFFICE_MASTER_STYLES,
  OFFICE_SETTINGS,
  OFFICE_SCRIPTS,
  OFFICE_SPREADSHEET,
  OFFICE_VERSION,
  OFFICE_NAME,
  OFFICE_TARGET_FRAME_NAME,
  STYLE_DEFAULT_STYLE,
  STYLE_DEFAULT_PAGE_LAYOUT,
  STYLE_PAGE_LAYOUT,
  STYLE_PAGE_LAYOUT_PROPERTIES,
  STYLE_MASTER_PAGE,
  STYLE_STYLE,
  STYLE_FONT_FACE,
  STYLE_PARAGRAPH_PROPERTIES,
  STYLE_TEXT_PROPERTIES,
  STYLE_LIST_LEVEL_PROPERTIES,
  STYLE_LIST_LEVEL_LABEL_ALIGNMENT,
  STYLE_NAME,
  STYLE_DISPLAY_NAME,
  STYLE_FAMILY,
  STYLE_CLASS,
  STYLE_DEFAULT_OUTLINE_LEVEL,
  STYLE_FONT_FAMILY_GENERIC,
  STYLE_FONT_PITCH,
  STYLE_FONT_CHARSET,
  STYLE_NEXT_STYLE_NAME,
  STYLE_PARENT_STYLE_NAME,
  STYLE_PAGE_LAYOUT_NAME,
  STYLE_PRINT_ORIENTATION,
  STYLE_NUM_FORMAT,
  STYLE_NUM_LETTER_SYNC,
  STYLE_NUM_SUFFIX,
  STYLE_FONT_WEIGHT_ASIAN,
  STYLE_FONT_WEIGHT_COMPLEX,
  STYLE_FONT_STYLE_ASIAN,
  STYLE_FONT_STYLE_COMPLEX,
  STYLE_FONT_NAME,
  STYLE_FONT_NAME_ASIAN,
  STYLE_FONT_NAME_COMPLEX,
  STYLE_TEXT_UNDERLINE_STYLE,
  STYLE_TEXT_UNDERLINE_WIDTH,
  STYLE_USE_WINDOW_FONT_COLOR,
  STYLE_CONTEXTUAL_SPACING,
  STYLE_LINE_HEIGHT_AT_LEAST,
  STYLE_LINE_SPACING,
  STYLE_FONT_INDEPENDENT_LINE_SPACING,
  STYLE_TAB_STOPS,
  STYLE_TAB_STOP,
  STYLE_POSITION,
  STYLE_TYPE,
  STYLE_CHAR,
  STYLE_LEADER_STYLE,
  STYLE_LEADER_TEXT,
  TEXT_LIST_STYLE,
  TEXT_OUTLINE_STYLE,
  TEXT_LINENUMBERING_CONFIGURATION,
  TEXT_LINENUMBERING_SEPARATOR,
  TEXT_COUNT_EMPTY_LINES,
  TEXT_COUNT_IN_TEXT_BOXES,
  TEXT_RESTART_ON_PAGE,
  TEXT_OFFSET,
  TEXT_NUMBER_POSITION,
  TEXT_INCREMENT,
  TEXT_NOTES_CONFIGURATION,
  TEXT_LIST_LEVEL_STYLE_BULLET,
  TEXT_LIST_LEVEL_STYLE_NUMBER,
  TEXT_SEQUENCE_DECLS,
  TEXT_P,
  TEXT_H,
  TEXT_LIST,
  TEXT_LIST_ITEM,
  TEXT_LIST_HEADER,
  TEXT_SECTION,
  TEXT_A,
  TEXT_SPAN,
  TEXT_S,
  TEXT_TAB,
  TEXT_LINE_BREAK,
  TEXT_STYLE_NAME,
  TEXT_CONTINUE_LIST,
  TEXT_START_VALUE,
  TEXT_LEVEL,
  TEXT_BULLET_CHAR,
  TEXT_LABEL_FOLLOWED_BY,
  TEXT_LIST_TAB_STOP_POSITION,
  TEXT_SPACE_BEFORE,
  TEXT_MIN_LABEL_WIDTH,
  TEXT_MIN_LABEL_DISTANCE,
  TEXT_C,
  TEXT_OUTLINE_LEVEL,
  TEXT_VISITED_STYLE_NAME,
  TEXT_NUMBER_LINES,
  TEXT_DISPLAY_OUTLINE_LEVEL,
  LOEXT_THEME,
  XLINK_HREF,
  XLINK_SHOW,
  XLINK_TYPE,
  FO_TEXT_ALIGN,
  FO_MARGIN_LEFT,
  FO_MARGIN_RIGHT,
  FO_MARGIN_TOP,
  FO_MARGIN_BOTTOM,
  FO_TEXT_INDENT,
  FO_LINE_HEIGHT,
  FO_FONT_WEIGHT,
  FO_FONT_STYLE,
  FO_FONT_FAMILY,
  FO_FONT_SIZE,
  FO_COLOR,
  FO_BACKGROUND_COLOR,
  FO_KEEP_WITH_NEXT,
  FO_PAGE_WIDTH,
  FO_PAGE_HEIGHT,
  SVG_FONT_FAMILY,
  DC_TITLE,
  DC_LANGUAGE,
  DC_CREATOR,
  DC_DATE,
  META_GENERATOR,
  META_INITIAL_CREATOR,
  META_CREATION_DATE,
  META_EDITING_CYCLES,
  META_EDITING_DURATION,
  META_DOCUMENT_STATISTIC,
  XML_ID,
  STYLE_LIST_STYLE_NAME,
}

const entries: readonly (readonly [string, string, XMLToken])[] = [
  [ODF_NAMESPACES.office, "document-styles", XMLToken.OFFICE_DOCUMENT_STYLES],
  [ODF_NAMESPACES.office, "document-content", XMLToken.OFFICE_DOCUMENT_CONTENT],
  [ODF_NAMESPACES.office, "document-meta", XMLToken.OFFICE_DOCUMENT_META],
  [ODF_NAMESPACES.office, "styles", XMLToken.OFFICE_STYLES],
  [ODF_NAMESPACES.office, "automatic-styles", XMLToken.OFFICE_AUTOMATIC_STYLES],
  [ODF_NAMESPACES.office, "body", XMLToken.OFFICE_BODY],
  [ODF_NAMESPACES.office, "text", XMLToken.OFFICE_TEXT],
  [ODF_NAMESPACES.office, "meta", XMLToken.OFFICE_META],
  [ODF_NAMESPACES.office, "font-face-decls", XMLToken.OFFICE_FONT_FACE_DECLS],
  [ODF_NAMESPACES.office, "master-styles", XMLToken.OFFICE_MASTER_STYLES],
  [ODF_NAMESPACES.office, "settings", XMLToken.OFFICE_SETTINGS],
  [ODF_NAMESPACES.office, "scripts", XMLToken.OFFICE_SCRIPTS],
  [ODF_NAMESPACES.office, "spreadsheet", XMLToken.OFFICE_SPREADSHEET],
  [ODF_NAMESPACES.office, "version", XMLToken.OFFICE_VERSION],
  [ODF_NAMESPACES.office, "name", XMLToken.OFFICE_NAME],
  [ODF_NAMESPACES.office, "target-frame-name", XMLToken.OFFICE_TARGET_FRAME_NAME],
  [ODF_NAMESPACES.style, "default-style", XMLToken.STYLE_DEFAULT_STYLE],
  [ODF_NAMESPACES.style, "default-page-layout", XMLToken.STYLE_DEFAULT_PAGE_LAYOUT],
  [ODF_NAMESPACES.style, "page-layout", XMLToken.STYLE_PAGE_LAYOUT],
  [ODF_NAMESPACES.style, "page-layout-properties", XMLToken.STYLE_PAGE_LAYOUT_PROPERTIES],
  [ODF_NAMESPACES.style, "master-page", XMLToken.STYLE_MASTER_PAGE],
  [ODF_NAMESPACES.style, "style", XMLToken.STYLE_STYLE],
  [ODF_NAMESPACES.style, "font-face", XMLToken.STYLE_FONT_FACE],
  [ODF_NAMESPACES.style, "paragraph-properties", XMLToken.STYLE_PARAGRAPH_PROPERTIES],
  [ODF_NAMESPACES.style, "text-properties", XMLToken.STYLE_TEXT_PROPERTIES],
  [ODF_NAMESPACES.style, "list-level-properties", XMLToken.STYLE_LIST_LEVEL_PROPERTIES],
  [ODF_NAMESPACES.style, "list-level-label-alignment", XMLToken.STYLE_LIST_LEVEL_LABEL_ALIGNMENT],
  [ODF_NAMESPACES.style, "name", XMLToken.STYLE_NAME],
  [ODF_NAMESPACES.style, "display-name", XMLToken.STYLE_DISPLAY_NAME],
  [ODF_NAMESPACES.style, "family", XMLToken.STYLE_FAMILY],
  [ODF_NAMESPACES.style, "class", XMLToken.STYLE_CLASS],
  [ODF_NAMESPACES.style, "default-outline-level", XMLToken.STYLE_DEFAULT_OUTLINE_LEVEL],
  [ODF_NAMESPACES.style, "font-family-generic", XMLToken.STYLE_FONT_FAMILY_GENERIC],
  [ODF_NAMESPACES.style, "font-pitch", XMLToken.STYLE_FONT_PITCH],
  [ODF_NAMESPACES.style, "font-charset", XMLToken.STYLE_FONT_CHARSET],
  [ODF_NAMESPACES.style, "next-style-name", XMLToken.STYLE_NEXT_STYLE_NAME],
  [ODF_NAMESPACES.style, "parent-style-name", XMLToken.STYLE_PARENT_STYLE_NAME],
  [ODF_NAMESPACES.style, "list-style-name", XMLToken.STYLE_LIST_STYLE_NAME],
  [ODF_NAMESPACES.style, "page-layout-name", XMLToken.STYLE_PAGE_LAYOUT_NAME],
  [ODF_NAMESPACES.style, "print-orientation", XMLToken.STYLE_PRINT_ORIENTATION],
  [ODF_NAMESPACES.style, "num-format", XMLToken.STYLE_NUM_FORMAT],
  [ODF_NAMESPACES.style, "num-letter-sync", XMLToken.STYLE_NUM_LETTER_SYNC],
  [ODF_NAMESPACES.style, "num-suffix", XMLToken.STYLE_NUM_SUFFIX],
  [ODF_NAMESPACES.style, "font-weight-asian", XMLToken.STYLE_FONT_WEIGHT_ASIAN],
  [ODF_NAMESPACES.style, "font-weight-complex", XMLToken.STYLE_FONT_WEIGHT_COMPLEX],
  [ODF_NAMESPACES.style, "font-style-asian", XMLToken.STYLE_FONT_STYLE_ASIAN],
  [ODF_NAMESPACES.style, "font-style-complex", XMLToken.STYLE_FONT_STYLE_COMPLEX],
  [ODF_NAMESPACES.style, "font-name", XMLToken.STYLE_FONT_NAME],
  [ODF_NAMESPACES.style, "font-name-asian", XMLToken.STYLE_FONT_NAME_ASIAN],
  [ODF_NAMESPACES.style, "font-name-complex", XMLToken.STYLE_FONT_NAME_COMPLEX],
  [ODF_NAMESPACES.style, "text-underline-style", XMLToken.STYLE_TEXT_UNDERLINE_STYLE],
  [ODF_NAMESPACES.style, "text-underline-width", XMLToken.STYLE_TEXT_UNDERLINE_WIDTH],
  [ODF_NAMESPACES.style, "use-window-font-color", XMLToken.STYLE_USE_WINDOW_FONT_COLOR],
  [ODF_NAMESPACES.style, "contextual-spacing", XMLToken.STYLE_CONTEXTUAL_SPACING],
  [ODF_NAMESPACES.style, "line-height-at-least", XMLToken.STYLE_LINE_HEIGHT_AT_LEAST],
  [ODF_NAMESPACES.style, "line-spacing", XMLToken.STYLE_LINE_SPACING],
  [
    ODF_NAMESPACES.style,
    "font-independent-line-spacing",
    XMLToken.STYLE_FONT_INDEPENDENT_LINE_SPACING,
  ],
  [ODF_NAMESPACES.style, "tab-stops", XMLToken.STYLE_TAB_STOPS],
  [ODF_NAMESPACES.style, "tab-stop", XMLToken.STYLE_TAB_STOP],
  [ODF_NAMESPACES.style, "position", XMLToken.STYLE_POSITION],
  [ODF_NAMESPACES.style, "type", XMLToken.STYLE_TYPE],
  [ODF_NAMESPACES.style, "char", XMLToken.STYLE_CHAR],
  [ODF_NAMESPACES.style, "leader-style", XMLToken.STYLE_LEADER_STYLE],
  [ODF_NAMESPACES.style, "leader-text", XMLToken.STYLE_LEADER_TEXT],
  [ODF_NAMESPACES.text, "list-style", XMLToken.TEXT_LIST_STYLE],
  [ODF_NAMESPACES.text, "outline-style", XMLToken.TEXT_OUTLINE_STYLE],
  [ODF_NAMESPACES.text, "linenumbering-configuration", XMLToken.TEXT_LINENUMBERING_CONFIGURATION],
  [ODF_NAMESPACES.text, "linenumbering-separator", XMLToken.TEXT_LINENUMBERING_SEPARATOR],
  [ODF_NAMESPACES.text, "count-empty-lines", XMLToken.TEXT_COUNT_EMPTY_LINES],
  [ODF_NAMESPACES.text, "count-in-text-boxes", XMLToken.TEXT_COUNT_IN_TEXT_BOXES],
  [ODF_NAMESPACES.text, "restart-on-page", XMLToken.TEXT_RESTART_ON_PAGE],
  [ODF_NAMESPACES.text, "offset", XMLToken.TEXT_OFFSET],
  [ODF_NAMESPACES.text, "number-position", XMLToken.TEXT_NUMBER_POSITION],
  [ODF_NAMESPACES.text, "increment", XMLToken.TEXT_INCREMENT],
  [ODF_NAMESPACES.text, "notes-configuration", XMLToken.TEXT_NOTES_CONFIGURATION],
  [ODF_NAMESPACES.text, "list-level-style-bullet", XMLToken.TEXT_LIST_LEVEL_STYLE_BULLET],
  [ODF_NAMESPACES.text, "list-level-style-number", XMLToken.TEXT_LIST_LEVEL_STYLE_NUMBER],
  [ODF_NAMESPACES.text, "sequence-decls", XMLToken.TEXT_SEQUENCE_DECLS],
  [ODF_NAMESPACES.text, "p", XMLToken.TEXT_P],
  [ODF_NAMESPACES.text, "h", XMLToken.TEXT_H],
  [ODF_NAMESPACES.text, "list", XMLToken.TEXT_LIST],
  [ODF_NAMESPACES.text, "list-item", XMLToken.TEXT_LIST_ITEM],
  [ODF_NAMESPACES.text, "list-header", XMLToken.TEXT_LIST_HEADER],
  [ODF_NAMESPACES.text, "section", XMLToken.TEXT_SECTION],
  [ODF_NAMESPACES.text, "a", XMLToken.TEXT_A],
  [ODF_NAMESPACES.text, "span", XMLToken.TEXT_SPAN],
  [ODF_NAMESPACES.text, "s", XMLToken.TEXT_S],
  [ODF_NAMESPACES.text, "tab", XMLToken.TEXT_TAB],
  [ODF_NAMESPACES.text, "line-break", XMLToken.TEXT_LINE_BREAK],
  [ODF_NAMESPACES.text, "style-name", XMLToken.TEXT_STYLE_NAME],
  [ODF_NAMESPACES.text, "continue-list", XMLToken.TEXT_CONTINUE_LIST],
  [ODF_NAMESPACES.text, "start-value", XMLToken.TEXT_START_VALUE],
  [ODF_NAMESPACES.text, "level", XMLToken.TEXT_LEVEL],
  [ODF_NAMESPACES.text, "bullet-char", XMLToken.TEXT_BULLET_CHAR],
  [ODF_NAMESPACES.text, "label-followed-by", XMLToken.TEXT_LABEL_FOLLOWED_BY],
  [ODF_NAMESPACES.text, "list-tab-stop-position", XMLToken.TEXT_LIST_TAB_STOP_POSITION],
  [ODF_NAMESPACES.text, "space-before", XMLToken.TEXT_SPACE_BEFORE],
  [ODF_NAMESPACES.text, "min-label-width", XMLToken.TEXT_MIN_LABEL_WIDTH],
  [ODF_NAMESPACES.text, "min-label-distance", XMLToken.TEXT_MIN_LABEL_DISTANCE],
  [ODF_NAMESPACES.text, "c", XMLToken.TEXT_C],
  [ODF_NAMESPACES.text, "outline-level", XMLToken.TEXT_OUTLINE_LEVEL],
  [ODF_NAMESPACES.text, "visited-style-name", XMLToken.TEXT_VISITED_STYLE_NAME],
  [ODF_NAMESPACES.text, "number-lines", XMLToken.TEXT_NUMBER_LINES],
  [ODF_NAMESPACES.text, "display-outline-level", XMLToken.TEXT_DISPLAY_OUTLINE_LEVEL],
  [ODF_NAMESPACES.loext, "theme", XMLToken.LOEXT_THEME],
  [ODF_NAMESPACES.xlink, "href", XMLToken.XLINK_HREF],
  [ODF_NAMESPACES.xlink, "show", XMLToken.XLINK_SHOW],
  [ODF_NAMESPACES.xlink, "type", XMLToken.XLINK_TYPE],
  [ODF_NAMESPACES.fo, "text-align", XMLToken.FO_TEXT_ALIGN],
  [ODF_NAMESPACES.fo, "margin-left", XMLToken.FO_MARGIN_LEFT],
  [ODF_NAMESPACES.fo, "margin-right", XMLToken.FO_MARGIN_RIGHT],
  [ODF_NAMESPACES.fo, "margin-top", XMLToken.FO_MARGIN_TOP],
  [ODF_NAMESPACES.fo, "margin-bottom", XMLToken.FO_MARGIN_BOTTOM],
  [ODF_NAMESPACES.fo, "text-indent", XMLToken.FO_TEXT_INDENT],
  [ODF_NAMESPACES.fo, "line-height", XMLToken.FO_LINE_HEIGHT],
  [ODF_NAMESPACES.fo, "font-weight", XMLToken.FO_FONT_WEIGHT],
  [ODF_NAMESPACES.fo, "font-style", XMLToken.FO_FONT_STYLE],
  [ODF_NAMESPACES.fo, "font-family", XMLToken.FO_FONT_FAMILY],
  [ODF_NAMESPACES.fo, "font-size", XMLToken.FO_FONT_SIZE],
  [ODF_NAMESPACES.fo, "color", XMLToken.FO_COLOR],
  [ODF_NAMESPACES.fo, "background-color", XMLToken.FO_BACKGROUND_COLOR],
  [ODF_NAMESPACES.fo, "keep-with-next", XMLToken.FO_KEEP_WITH_NEXT],
  [ODF_NAMESPACES.fo, "page-width", XMLToken.FO_PAGE_WIDTH],
  [ODF_NAMESPACES.fo, "page-height", XMLToken.FO_PAGE_HEIGHT],
  [ODF_NAMESPACES.svg, "font-family", XMLToken.SVG_FONT_FAMILY],
  [ODF_NAMESPACES.dc, "title", XMLToken.DC_TITLE],
  [ODF_NAMESPACES.dc, "language", XMLToken.DC_LANGUAGE],
  [ODF_NAMESPACES.dc, "creator", XMLToken.DC_CREATOR],
  [ODF_NAMESPACES.dc, "date", XMLToken.DC_DATE],
  [ODF_NAMESPACES.meta, "generator", XMLToken.META_GENERATOR],
  [ODF_NAMESPACES.meta, "initial-creator", XMLToken.META_INITIAL_CREATOR],
  [ODF_NAMESPACES.meta, "creation-date", XMLToken.META_CREATION_DATE],
  [ODF_NAMESPACES.meta, "editing-cycles", XMLToken.META_EDITING_CYCLES],
  [ODF_NAMESPACES.meta, "editing-duration", XMLToken.META_EDITING_DURATION],
  [ODF_NAMESPACES.meta, "document-statistic", XMLToken.META_DOCUMENT_STATISTIC],
  [ODF_NAMESPACES.xml, "id", XMLToken.XML_ID],
];

const tokens = new Map(
  entries.map(
    /** Creates one expanded-name lookup entry. @param entry - Namespace, local name, and token. @returns Lookup pair. */
    ([namespaceURI, localName, token]) => [`${namespaceURI}\0${localName}`, token],
  ),
);

/** Resolves an expanded XML name. @param namespaceURI - Namespace URI. @param localName - Local name. @returns Stable token. */
export function getXMLToken(namespaceURI: string, localName: string): XMLToken {
  return tokens.get(`${namespaceURI}\0${localName}`) ?? XMLToken.UNKNOWN;
}
